### ISSUE TITLE
Not possible to authenticate 

### ISSUE THREAD

**Issue by alitis76** [ashishtank/MMM-MercedesMe#2]
Hello, 

I have followed the instructions as described. 
I get to the point from where I should click Authenticate. 
When I do that nothing happens. 

When I stop the MM and enter in the browser localhost:8080/MMM-MercedesMe/auth I get the message that the connection was refused. 

I can see the following details in my logs :

TypeError: Cannot read property 'getToken' of null
    at Class.handleCallback (/home/pi/MagicMirror/modules/MMM-MercedesMe/node_helper.js:63:21)
    at Layer.handle [as handle_request] (/home/pi/MagicMirror/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/MagicMirror/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/pi/MagicMirror/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pi/MagicMirror/node_modules/express/lib/router/layer.js:95:5)
    at /home/pi/MagicMirror/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/pi/MagicMirror/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/MagicMirror/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/pi/MagicMirror/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:400:28)

**Comment by ashishtank** [comment]
Hi @alitis76 

could you check if request node module is installed ? you can ran below command to install request node module.

`npm install request OAuth --save`

you can not directy open the url in browser as Authclient might not be initilized and when you stop the MM the website is also stopped so it will not work. Hope above will sovle the issue.

Regards,
Ashish

**Comment by alitis76** [comment]
Hello Ashish, 

after typing it as 
"npm install request oauth --save"  (not with capital letters) the installation works. 

But still the same problem. 
I am not able to authenticate. 
When I do a "mouse-over" on the Autheticate-link, I can see the (localhost:8080/MercedesMe/auth). 
After I click on it nothing happens.

I have start the MagicMirror now with the option server only. 

In this case I receive the following log

[16.08.2021 11:34.40.796] [LOG]   Handle OAuth callback
[16.08.2021 11:34.40.859] [ERROR] TypeError: Cannot read property 'getToken' of null
    at Class.handleCallback (/home/pi/MagicMirror/modules/MMM-MercedesMe/node_helper.js:63:21)
    at Layer.handle [as handle_request] (/home/pi/MagicMirror/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/MagicMirror/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/pi/MagicMirror/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pi/MagicMirror/node_modules/express/lib/router/layer.js:95:5)
    at /home/pi/MagicMirror/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/pi/MagicMirror/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/MagicMirror/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/pi/MagicMirror/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:400:28)
[16.08.2021 11:34.53.268] [LOG]   Handle OAuth request
[16.08.2021 11:35.35.514] [LOG]   Create new calendarfetcher for url: http://mxxxxxxxxxxxxxxxxxxxxxxxxxxxxxcalendar.ics - Interval: 300000
[16.08.2021 11:35.36.108] [LOG]   SET Config received
[16.08.2021 11:35.36.111] [LOG]   Init token from file./modules/MMM-MercedesMe/tokens.json
[16.08.2021 11:35.36.116] [LOG]   No token file found
[16.08.2021 11:35.36.145] [LOG]   Create new newsfetcher for url: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
[16.08.2021 11:35.36.203] [INFO]  Checking git for module: MMM-MercedesMe
[16.08.2021 11:35.37.027] [INFO]  Newsfeed-Fetcher: Broadcasting 9 items.
[16.08.2021 11:35.38.126] [INFO]  Calendar-Fetcher: Broadcasting 10 events.



Is it possible that I have to install a token.json file first before I can authenticate it? 

_[16.08.2021 11:35.36.111] [LOG]   Init token from file./modules/MMM-MercedesMe/tokens.json
[16.08.2021 11:35.36.116] [LOG]   No token file found_

Maybe the module doesn´t like me so that I can not use it :-( 


Regards 
alitis76

**Comment by alitis76** [comment]
Hello, 

coincidentally, I have just discovered the following

I have entered a wrong clientID in config.js.
When I started the MM again it started normally. 

When I clicked on Authenticate I got the following message on the mirror:



Error
Oops
Looks like something is not right. Please contact your administrator.
400 - Invalid client_id

As soon as I paste the correct "client ID" and the correct "client secret" and restart the MM I can see the Authenticate link but after I click on it nothing happens.

Regards 
alitis76

**Comment by ashishtank** [comment]
Hi @alitis76 

There is no log in MM console ? Could you open the browser dev tools (Press F12) before you click on authenticate link and check the network traffic and browser console ? It could be that previous cookies are still saved and thus the authentication session of Mercedes is not working correctly. In that case you can also try clearing the cookies and then authenticate again.

Regards,
Ashish

**Comment by alitis76** [comment]
Hi, 

it looks that the module doesn´t  like me :) 

I have format my sd card and have install the MM again from the beginning.
Before I installed some other modules I have try it with the MM-MercedesMe module (install it to my MM). 
Then I have create a new MercedeMe account (merge it as subaccount to my existing account).

With the new Account I have follow the steps (Developer.Mercedes.Me.......... etc.)
At the point authentication I have start the browser dev-tools.
Then I ´ve click to the authenticate link (the result is the same as before (nothing happens) it´s depressing) :) 


In the log of MM i found this: 

[27.08.2021 11:20.18.410] [LOG]   Handle OAuth request
[27.08.2021 11:20.26.105] [LOG]   SET Config received
[27.08.2021 11:20.26.108] [LOG]   Init token from file./modules/MMM-MercedesMe/tokens.json
[27.08.2021 11:20.26.110] [LOG]   No token file found

In the browser dev I see the following : 
![dev-tools](https://user-images.githubusercontent.com/64280477/131122206-d54f6aa6-12c5-4e37-bf47-619ea0137df4.JPG)

The output looks 

[dev-tools-output_bearb.txt](https://github.com/ashishtank/MMM-MercedesMe/files/7066670/dev-tools-output_bearb.txt)

**Comment by ashishtank** [comment]
Hi @alitis76 
lets connect offline to check this. could you ping me on magic mirror foram chat ?

**Comment by ashishtank** [comment]
@alitis76 I just checked and it is not working for me as well from Postman to get new token. This looks like an issue in Mercedes api. When i only select offline_access scope i am able to get the token but that is not sufficient to work with Mercedes Api. we also need ev status or fuel status in scope. Could you send them email that how the scope should be sent in request ? right now we are sending scope as below 

https://id.mercedes-benz.com/as/authorization.oauth2?response_type=code&client_id=7dbee8cf-0087-4d5a-9236-057f796ce803&scope=mb%3Avehicle%3Ambdata%3Aevstatus%20offline_access&redirect_uri=https%3A%2F%2Foauth.pstmn.io%2Fv1%2Fcallback

 `mb:vehicle:mbdata:evstatus offline_access`

**Comment by ashishtank** [comment]
@alitis76 I emailed Mercedes and we found that `mb:vehicle:mbdata:evstatus` scope is not working. I have emailed them to check.

**Comment by ashishtank** [comment]
@alitis76 after linking correct scope now i am able to get the token. could you please share screenshot of your app configuration ? offcourse by hiding client id and secret :)

**Comment by alitis76** [comment]
I'm sorry I'm so late getting back to you but I'm in the process of moving to a new appartment.
It´s a hard time :)



`		{
      			module: 'MMM-MercedesMe',
      			position: 'bottom_left',
      			header: 'My Mercedes',
      			config: {
              			client_id: 'XXXXX-YYYYY-ZZZZZ-1234567890',
              			client_secret: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
              			vehicleType: 'Petrol',
              			vehicleId: 'WDD177XXXXXXXXXXX',
              			displayStyle: 'twodial',
              			maxRange: 110
      				}		
		},
`

![MMM_MercedesMe](https://user-images.githubusercontent.com/64280477/132052853-441ba67c-2c98-433f-b7d6-76b5af730d6f.JPG)

**Comment by ashishtank** [comment]
@alitis76 got it, the issue is with the vehicle type. can you make it `diesel` and try again (it does not matter for MM if your car is actully petrol :) ) ? i will correct it in next version. It should work after changing the vehicle type.
